const globals = require('globals');
const js = require('@eslint/js'); // ESLint's built-in recommended rules
const jest = require('eslint-plugin-jest'); // Import Jest Plugin

module.exports = [
    js.configs.recommended, // Include ESLint recommended rules
    {
        files: ['**/*.js'],
        languageOptions: {
            sourceType: 'commonjs',
            globals: {
                ...globals.node,
                ...globals.jest, // Add Jest globals
            },
        },
        plugins: {
            jest, // Flat config requires plugins to be an object, not an array
        },
        rules: {
            'constructor-super': 'error',
            'for-direction': 'error',
            'getter-return': 'off',
            'no-async-promise-executor': 'error',
            'no-case-declarations': 'error',
            'no-class-assign': 'error',
            'no-compare-neg-zero': 'error',
            'no-cond-assign': ['error', 'except-parens'],
            'no-const-assign': 'error',
            'no-constant-binary-expression': 'error',
            'no-constant-condition': [
                'error',
                { checkLoops: 'allExceptWhileTrue' },
            ],
            'no-control-regex': 'off',
            'no-debugger': 'error',
            'no-delete-var': 'off',
            'no-dupe-args': 'error',
            'no-dupe-class-members': 'error',
            'no-dupe-else-if': 'error',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-empty': ['error', { allowEmptyCatch: false }],
            'no-empty-character-class': 'error',
            'no-empty-pattern': [
                'error',
                { allowObjectPatternsAsParameters: false },
            ],
            'no-empty-static-block': 'error',
            'no-ex-assign': 'error',
            'no-extra-boolean-cast': 'error',
            'no-fallthrough': 'off',
            'no-func-assign': 'error',
            'no-global-assign': 'error',
            'no-import-assign': 'error',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': [
                'error',
                {
                    skipComments: false,
                    skipJSXText: false,
                    skipRegExps: false,
                    skipStrings: true,
                    skipTemplates: false,
                },
            ],
            'no-loss-of-precision': 'error',
            'no-misleading-character-class': 'error',
            'no-new-native-nonconstructor': 'error',
            'no-nonoctal-decimal-escape': 'error',
            'no-obj-calls': 'error',
            'no-octal': 'error',
            'no-prototype-builtins': 'off',
            'no-redeclare': ['error', { builtinGlobals: true }],
            'no-regex-spaces': 'error',
            'no-self-assign': ['error', { props: true }],
            'no-setter-return': 'error',
            'no-shadow-restricted-names': 'error',
            'no-sparse-arrays': 'error',
            'no-this-before-super': 'error',
            'no-undef': ['error', { typeof: false }],
            'no-unexpected-multiline': 'error',
            'no-unreachable': 'error',
            'no-unsafe-finally': 'error',
            'no-unsafe-negation': [
                'error',
                { enforceForOrderingRelations: false },
            ],
            'no-unsafe-optional-chaining': [
                'error',
                { disallowArithmeticOperators: false },
            ],
            'no-unused-labels': 'error',
            'no-unused-private-class-members': 'error',
            'no-unused-vars': [
                'error',
                {
                    varsIgnorePattern: '^_',
                    argsIgnorePattern: '^_',
                    caughtErrorsIgnorePattern: '^_',
                },
            ],
            'no-useless-backreference': 'error',
            'no-useless-catch': 'error',
            'no-useless-escape': 'error',
            'no-with': 'error',
            'require-yield': 'error',
            'use-isnan': [
                'error',
                { enforceForIndexOf: false, enforceForSwitchCase: true },
            ],
            'valid-typeof': ['error', { requireStringLiterals: false }],
            'prefer-const': [
                'error',
                { destructuring: 'any', ignoreReadBeforeAssign: false },
            ],
            'no-var': 'error',
            'object-shorthand': 'error',
            'no-array-constructor': 'error',
            'prefer-destructuring': 'error',
            'prefer-template': 'error',
            'no-eval': ['error', { allowIndirect: false }],
            'prefer-object-spread': 'error',
            'prefer-spread': 'error',
            'array-callback-return': [
                'error',
                { allowImplicit: false, checkForEach: false, allowVoid: false },
            ],
            'no-loop-func': 'error',
            'prefer-rest-params': 'error',
            'no-useless-constructor': 'error',
            'no-duplicate-imports': ['error', { includeExports: false }],
            'no-multi-assign': ['error', { ignoreNonDeclaration: false }],
            'no-unneeded-ternary': ['error', { defaultAssignment: true }],
            'no-else-return': ['error', { allowElseIf: true }],
            'no-new-wrappers': 'error',
            'no-use-before-define': [
                'error',
                {
                    classes: true,
                    functions: false,
                    variables: true,
                    allowNamedExports: false,
                },
            ],
        },
    },
];
